---
- name: Deploy with maven
  hosts: VM-tomcat

  tasks:
    - name: Install maven
      become: yes
      pacman:
        state: present
        name: maven

    - name: Clone spring-mvc repo
      git:
        repo: 'https://github.com/AleksandarStojanovikj/spring-mvc.git'
        dest: /home/test/spring-mvc

    - name: Run mvn clean install
      shell: mvn clean install
      args: 
        chdir: /home/test/spring-mvc

    - name: Remove old deployed war
      become: yes
      file:
        path: /usr/share/tomcat8/webapps/mvc.war
        state: absent
    
    - name: Deploy spring-mvc.war to tomcat
      become: yes
      copy:
        remote_src: yes
        src: /home/test/spring-mvc/target/mvc.war
        dest: /usr/share/tomcat8/webapps/mvc.war
