---
- name: Tomcat stack
  hosts: VM-tomcat
  become: yes

  tasks:
    - name: Full system upgrade
      tags: ["system"]
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install tomcat
      tags: ["tomcat"]
      pacman:
        state: present
        name: tomcat8

    - name: Install git
      pacman: 
        state: present
        name: git

    - name: Start tomcat
      service:
        name: tomcat8
        state: started
