---
- name: mariadb configuration
  hosts: VM
  become: yes
  vars:
    mariadb_root_password: 'root'
    mariadb_socket: '/var/run/mysqld/mysqld.sock'

  tasks:
    - name: Install mariadb
      tags: ["mariadb"]
      pacman:
        state: present
        name:
          - mariadb
          - python-pymysql

    - name: Count files in /var/lib/mysql
      find: path=/var/lib/mysql patterns="*"
      register: db_files

    - name: Run mariadb-install-db only if /var/lib/mysql is empty
      command: mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
      when: db_files.matched|int == 0

    - name: Start mariadb
      service:
        name: mariadb
        state: started

    - name: Is root password set?
      command: mysql -u root --execute "SELECT NOW()"
      register: is_root_password_set
      ignore_errors: yes
      no_log: true

    - name: Set root password
      mysql_user:
        user: root
        password: "{{ mariadb_root_password }}"
        host: localhost
        login_unix_socket: "{{ mariadb_socket }}"
      when: is_root_password_set.rc == 0

    - name: Copy sakila-schema
      ansible.builtin.copy:
        src: sakila-schema.sql
        dest: "/tmp/sakila-schema.sql"
        owner: test
        mode: '0644'

    - name: Copy sakila-data
      ansible.builtin.copy:
        src: sakila-data.sql
        dest: "/tmp/sakila-data.sql"
        owner: test
        mode: '0644'

    - name: Import sakila schema
      mysql_db:
        state: import
        name: all
        target: /tmp/sakila-schema.sql
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Import sakila database
      mysql_db:
        state: import
        name: all
        target: /tmp/sakila-data.sql
        login_user: root
        login_password: "{{ mariadb_root_password }}"
