---
- name: PHP
  hosts: VM
  become: yes

  tasks:
    - name: Install php
      tags: ["php"]
      pacman:
        state: present
        name:
          - php
          - php-apache
    
    # Using libphp
    # https://wiki.archlinux.org/index.php/Apache_HTTP_Server#PHP
    - name: Comment mpm_event_module in httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^LoadModule mpm_event_module modules/mod_mpm_event.so'
        line: '#LoadModule mpm_event_module modules/mod_mpm_event.so'

    - name: Uncomment mpm_prefork_module in httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
        line: 'LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'

    - name: Enable php1
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: '#LoadModule rewrite_module modules/mod_rewrite.so'
        line: 'LoadModule php7_module modules/libphp7.so'

    - name: Enable php2
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: 'LoadModule php7_module modules/libphp7.so'
        line: 'AddHandler php7-script .php'

    - name: Enable php3
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "Include conf/extra/php7_module.conf"

    - name: Copy info page
      template:
        src: "templates/info.php.j2"
        dest: "/srv/http/domain2/info.php"

    - name: Enable mariadb in php.ini
      lineinfile:
        path: /etc/php/php.ini
        regexp: ';extension=pdo_mysql'
        line: 'extension=pdo_mysql'

    - name: Enable mariadb in php.ini
      lineinfile:
        path: /etc/php/php.ini
        regexp: ';extension=mysqli'
        line: 'extension=mysqli'

    - name: Restart httpd.service
      service:
        name: httpd
        state: reloaded